### ISSUE TITLE
Vorschläge zur Struktur: Namensgebung

### ISSUE THREAD

**Issue by christophboecker** [alexplusde/yform_fields#2]
Irgendwie müssen die Namen der Toolklassen, aber auch zugehörige lang-Einträge, css-Klassen, js-Zeugs sinnvoll und kollisionsfrei benannt werden. In erster Linie mal als Abgrenzung zu anderen Addons, aber auch intern in diesem Addon. 

Wie wäre es mit asyf für "alex seine yform fields" (und hier als Beispiel xyz für das jeweilige element

* Alle JS-Funktionen kommen in einer Klammerklasse `asyf`, werden also als `asyf.xyz_...` aufgerufen (belastet den Namensraum weniger).
* alle lang-Einträge beginnen mit `asyf_xyz_...`
* alle CSS-Elemente beginnen mit `asyf` wenn sie eine gewisse Allgemeingültigkeit haben, sonst `asyf-xyz-...`
* Klassen z.B. für Felder heißen `rex_yform_value_asyf_feldtyp`

Sach an ...

**Comment by alexplusde** [comment]
`rex_yform_fields_value_feldtyp` - das Addon heißt yform_fields und deswegen würde ich sagen, kann man das an den Anfang nehmen. Dürfte auch kollisionsfrei bleiben bis auf weiteres.

**Comment by christophboecker** [comment]
Hm, der Source-Code von rex_yform_manager hat z.B. in Zeile sowas:
```
if (method_exists('rex_yform_value_' . $field->getTypeName(), 'getListValue')) {
```
Daraus schließe ich, dass z.B. die Value-Klassen mit `rex_yform_value_` beginnen müssen. Also entweder einen kollisionsfreien Zwischenamen (meine Präferenz) oder mit z.B. Jan abstimmen, wie so Klassennamen konfliktfrei vergeben werden.

**Comment by alexplusde** [comment]
Ich bin noch frei darin, das Repo und Addon umzubenennen, falls das hilft. Der Zweck ist ja klar. `asyf` ist mir zu unsexy.

**Comment by christophboecker** [comment]
Wie das Addon später heißt und welches Kürzel man intern nimmt (Kürzel finde ich handlicher als lange Namen) ist mit egal. Sach was. Ich nur ne valide Vorgabe und will nur nicht später wieder den Code umbauen. Mein Arbeitsziel ist "fire and forget": ein PR und gut is. <grins>

**Comment by alexplusde** [comment]
Ich würde dann in aller Weitsicht vorschlagen `rex_yform_value_for_` für FriendsOfREDAXO, weil ich das Addon dahin übergeben werde, wenn es passt.

**Comment by christophboecker** [comment]
Der weise Mann sagt: es gibt FOR Alles eine Lösung!

**Comment by alexplusde** [comment]
lang analog dazu `rex_yform_value_for_`, css mit `for-fieldtype`, js denkst dir was aus und teilst es mir mit.
